services:
  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
      - loki-data:/loki
    networks:
      - loki-net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3100/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - loki
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-admin} # Use default 'admin' if not in .env
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin} # Use default 'admin' if not in .env
    networks:
      - loki-net

  log-ingestor:
    build: ./log-ingestor
    container_name: log-ingestor
    depends_on:
      loki:
        condition: service_healthy
    environment:
      - DXP_PROJECT_ID=${DXP_PROJECT_ID}
      - DXP_CLIENT_KEY=${DXP_CLIENT_KEY}
      - DXP_CLIENT_SECRET=${DXP_CLIENT_SECRET}
      - POLLING_INTERVAL=${POLLING_INTERVAL:-15000} # Default to 15 seconds if not in .env
    networks:
      - loki-net
    restart: unless-stopped

volumes:
  grafana-storage:
  loki-data: {}

networks:
  loki-net:
    driver: bridge 